! ------------------------------------------------------------------
! NB: Autogenerated. Do not modify manually.
! ------------------------------------------------------------------
module dataTypesInterface
   use DataTypes
   interface

   subroutine publish_null(id)
   ml_external publish_null
!STDCALL(publish_null)
   integer :: id
   end subroutine

   subroutine publish_feedItem(id, data)
   IMPORT :: feedItemType
   ml_external publish_feedItem
!STDCALL(publish_feedItem)
   integer :: id
   type(feedItemType) :: data
   end subroutine
   subroutine unpack_feedItem(variant, data)
   IMPORT :: feedItemType
   ml_external unpack_feedItem
!STDCALL(unpack_feedItem)
   integer :: variant
   type(feedItemType) :: data
   end subroutine
   subroutine publish_Manure(id, data)
   IMPORT :: ManureType
   ml_external publish_Manure
!STDCALL(publish_Manure)
   integer :: id
   type(ManureType) :: data
   end subroutine
   subroutine unpack_Manure(variant, data)
   IMPORT :: ManureType
   ml_external unpack_Manure
!STDCALL(unpack_Manure)
   integer :: variant
   type(ManureType) :: data
   end subroutine
   subroutine publish_plantItem(id, data)
   IMPORT :: plantItemType
   ml_external publish_plantItem
!STDCALL(publish_plantItem)
   integer :: id
   type(plantItemType) :: data
   end subroutine
   subroutine unpack_plantItem(variant, data)
   IMPORT :: plantItemType
   ml_external unpack_plantItem
!STDCALL(unpack_plantItem)
   integer :: variant
   type(plantItemType) :: data
   end subroutine
   subroutine publish_Sow(id, data)
   IMPORT :: SowType
   ml_external publish_Sow
!STDCALL(publish_Sow)
   integer :: id
   type(SowType) :: data
   end subroutine
   subroutine unpack_Sow(variant, data)
   IMPORT :: SowType
   ml_external unpack_Sow
!STDCALL(unpack_Sow)
   integer :: variant
   type(SowType) :: data
   end subroutine
   subroutine publish_SowPlant2(id, data)
   IMPORT :: SowPlant2Type
   ml_external publish_SowPlant2
!STDCALL(publish_SowPlant2)
   integer :: id
   type(SowPlant2Type) :: data
   end subroutine
   subroutine unpack_SowPlant2(variant, data)
   IMPORT :: SowPlant2Type
   ml_external unpack_SowPlant2
!STDCALL(unpack_SowPlant2)
   integer :: variant
   type(SowPlant2Type) :: data
   end subroutine
   subroutine publish_Establish(id, data)
   IMPORT :: EstablishType
   ml_external publish_Establish
!STDCALL(publish_Establish)
   integer :: id
   type(EstablishType) :: data
   end subroutine
   subroutine unpack_Establish(variant, data)
   IMPORT :: EstablishType
   ml_external unpack_Establish
!STDCALL(unpack_Establish)
   integer :: variant
   type(EstablishType) :: data
   end subroutine
   subroutine publish_Harvest(id, data)
   IMPORT :: HarvestType
   ml_external publish_Harvest
!STDCALL(publish_Harvest)
   integer :: id
   type(HarvestType) :: data
   end subroutine
   subroutine unpack_Harvest(variant, data)
   IMPORT :: HarvestType
   ml_external unpack_Harvest
!STDCALL(unpack_Harvest)
   integer :: variant
   type(HarvestType) :: data
   end subroutine
   subroutine publish_KillStem(id, data)
   IMPORT :: KillStemType
   ml_external publish_KillStem
!STDCALL(publish_KillStem)
   integer :: id
   type(KillStemType) :: data
   end subroutine
   subroutine unpack_KillStem(variant, data)
   IMPORT :: KillStemType
   ml_external unpack_KillStem
!STDCALL(unpack_KillStem)
   integer :: variant
   type(KillStemType) :: data
   end subroutine
   subroutine publish_Prune(id, data)
   IMPORT :: PruneType
   ml_external publish_Prune
!STDCALL(publish_Prune)
   integer :: id
   type(PruneType) :: data
   end subroutine
   subroutine unpack_Prune(variant, data)
   IMPORT :: PruneType
   ml_external unpack_Prune
!STDCALL(unpack_Prune)
   integer :: variant
   type(PruneType) :: data
   end subroutine
   subroutine publish_ApsimVariant(id, data)
   IMPORT :: ApsimVariantType
   ml_external publish_ApsimVariant
!STDCALL(publish_ApsimVariant)
   integer :: id
   type(ApsimVariantType) :: data
   end subroutine
   subroutine unpack_ApsimVariant(variant, data)
   IMPORT :: ApsimVariantType
   ml_external unpack_ApsimVariant
!STDCALL(unpack_ApsimVariant)
   integer :: variant
   type(ApsimVariantType) :: data
   end subroutine
   subroutine publish_Layered(id, data)
   IMPORT :: LayeredType
   ml_external publish_Layered
!STDCALL(publish_Layered)
   integer :: id
   type(LayeredType) :: data
   end subroutine
   subroutine unpack_Layered(variant, data)
   IMPORT :: LayeredType
   ml_external unpack_Layered
!STDCALL(unpack_Layered)
   integer :: variant
   type(LayeredType) :: data
   end subroutine
   subroutine publish_Time(id, data)
   IMPORT :: TimeType
   ml_external publish_Time
!STDCALL(publish_Time)
   integer :: id
   type(TimeType) :: data
   end subroutine
   subroutine unpack_Time(variant, data)
   IMPORT :: TimeType
   ml_external unpack_Time
!STDCALL(unpack_Time)
   integer :: variant
   type(TimeType) :: data
   end subroutine
   subroutine publish_NewMet(id, data)
   IMPORT :: NewMetType
   ml_external publish_NewMet
!STDCALL(publish_NewMet)
   integer :: id
   type(NewMetType) :: data
   end subroutine
   subroutine unpack_NewMet(variant, data)
   IMPORT :: NewMetType
   ml_external unpack_NewMet
!STDCALL(unpack_NewMet)
   integer :: variant
   type(NewMetType) :: data
   end subroutine
   subroutine publish_NewMetArrayelement(id, data)
   IMPORT :: NewMetArrayelementType
   ml_external publish_NewMetArrayelement
!STDCALL(publish_NewMetArrayelement)
   integer :: id
   type(NewMetArrayelementType) :: data
   end subroutine
   subroutine unpack_NewMetArrayelement(variant, data)
   IMPORT :: NewMetArrayelementType
   ml_external unpack_NewMetArrayelement
!STDCALL(unpack_NewMetArrayelement)
   integer :: variant
   type(NewMetArrayelementType) :: data
   end subroutine
   subroutine publish_NewMetArray(id, data)
   IMPORT :: NewMetArrayType
   ml_external publish_NewMetArray
!STDCALL(publish_NewMetArray)
   integer :: id
   type(NewMetArrayType) :: data
   end subroutine
   subroutine unpack_NewMetArray(variant, data)
   IMPORT :: NewMetArrayType
   ml_external unpack_NewMetArray
!STDCALL(unpack_NewMetArray)
   integer :: variant
   type(NewMetArrayType) :: data
   end subroutine
   subroutine publish_NewSolute(id, data)
   IMPORT :: NewSoluteType
   ml_external publish_NewSolute
!STDCALL(publish_NewSolute)
   integer :: id
   type(NewSoluteType) :: data
   end subroutine
   subroutine unpack_NewSolute(variant, data)
   IMPORT :: NewSoluteType
   ml_external unpack_NewSolute
!STDCALL(unpack_NewSolute)
   integer :: variant
   type(NewSoluteType) :: data
   end subroutine
   subroutine publish_CohortWaterDemandRootSystemLayer(id, data)
   IMPORT :: CohortWaterDemandRootSystemLayerType
   ml_external publish_CohortWaterDemandRootSystemLayer
!STDCALL(publish_CohortWaterDemandRootSystemLayer)
   integer :: id
   type(CohortWaterDemandRootSystemLayerType) :: data
   end subroutine
   subroutine unpack_CohortWaterDemandRootSystemLayer(variant, data)
   IMPORT :: CohortWaterDemandRootSystemLayerType
   ml_external unpack_CohortWaterDemandRootSystemLayer
!STDCALL(unpack_CohortWaterDemandRootSystemLayer)
   integer :: variant
   type(CohortWaterDemandRootSystemLayerType) :: data
   end subroutine
   subroutine publish_CohortWaterDemand(id, data)
   IMPORT :: CohortWaterDemandType
   ml_external publish_CohortWaterDemand
!STDCALL(publish_CohortWaterDemand)
   integer :: id
   type(CohortWaterDemandType) :: data
   end subroutine
   subroutine unpack_CohortWaterDemand(variant, data)
   IMPORT :: CohortWaterDemandType
   ml_external unpack_CohortWaterDemand
!STDCALL(unpack_CohortWaterDemand)
   integer :: variant
   type(CohortWaterDemandType) :: data
   end subroutine
   subroutine publish_CohortWaterSupplyRootSystemLayer(id, data)
   IMPORT :: CohortWaterSupplyRootSystemLayerType
   ml_external publish_CohortWaterSupplyRootSystemLayer
!STDCALL(publish_CohortWaterSupplyRootSystemLayer)
   integer :: id
   type(CohortWaterSupplyRootSystemLayerType) :: data
   end subroutine
   subroutine unpack_CohortWaterSupplyRootSystemLayer(variant, data)
   IMPORT :: CohortWaterSupplyRootSystemLayerType
   ml_external unpack_CohortWaterSupplyRootSystemLayer
!STDCALL(unpack_CohortWaterSupplyRootSystemLayer)
   integer :: variant
   type(CohortWaterSupplyRootSystemLayerType) :: data
   end subroutine
   subroutine publish_CohortWaterSupply(id, data)
   IMPORT :: CohortWaterSupplyType
   ml_external publish_CohortWaterSupply
!STDCALL(publish_CohortWaterSupply)
   integer :: id
   type(CohortWaterSupplyType) :: data
   end subroutine
   subroutine unpack_CohortWaterSupply(variant, data)
   IMPORT :: CohortWaterSupplyType
   ml_external unpack_CohortWaterSupply
!STDCALL(unpack_CohortWaterSupply)
   integer :: variant
   type(CohortWaterSupplyType) :: data
   end subroutine
   subroutine publish_FertiliserApplication(id, data)
   IMPORT :: FertiliserApplicationType
   ml_external publish_FertiliserApplication
!STDCALL(publish_FertiliserApplication)
   integer :: id
   type(FertiliserApplicationType) :: data
   end subroutine
   subroutine unpack_FertiliserApplication(variant, data)
   IMPORT :: FertiliserApplicationType
   ml_external unpack_FertiliserApplication
!STDCALL(unpack_FertiliserApplication)
   integer :: variant
   type(FertiliserApplicationType) :: data
   end subroutine
   subroutine publish_HillUp(id, data)
   IMPORT :: HillUpType
   ml_external publish_HillUp
!STDCALL(publish_HillUp)
   integer :: id
   type(HillUpType) :: data
   end subroutine
   subroutine unpack_HillUp(variant, data)
   IMPORT :: HillUpType
   ml_external unpack_HillUp
!STDCALL(unpack_HillUp)
   integer :: variant
   type(HillUpType) :: data
   end subroutine
   subroutine publish_KillCrop(id, data)
   IMPORT :: KillCropType
   ml_external publish_KillCrop
!STDCALL(publish_KillCrop)
   integer :: id
   type(KillCropType) :: data
   end subroutine
   subroutine unpack_KillCrop(variant, data)
   IMPORT :: KillCropType
   ml_external unpack_KillCrop
!STDCALL(unpack_KillCrop)
   integer :: variant
   type(KillCropType) :: data
   end subroutine
   subroutine publish_PhaseChanged(id, data)
   IMPORT :: PhaseChangedType
   ml_external publish_PhaseChanged
!STDCALL(publish_PhaseChanged)
   integer :: id
   type(PhaseChangedType) :: data
   end subroutine
   subroutine unpack_PhaseChanged(variant, data)
   IMPORT :: PhaseChangedType
   ml_external unpack_PhaseChanged
!STDCALL(unpack_PhaseChanged)
   integer :: variant
   type(PhaseChangedType) :: data
   end subroutine
   subroutine publish_KillLeaf(id, data)
   IMPORT :: KillLeafType
   ml_external publish_KillLeaf
!STDCALL(publish_KillLeaf)
   integer :: id
   type(KillLeafType) :: data
   end subroutine
   subroutine unpack_KillLeaf(variant, data)
   IMPORT :: KillLeafType
   ml_external unpack_KillLeaf
!STDCALL(unpack_KillLeaf)
   integer :: variant
   type(KillLeafType) :: data
   end subroutine
   subroutine publish_CropChopped(id, data)
   IMPORT :: CropChoppedType
   ml_external publish_CropChopped
!STDCALL(publish_CropChopped)
   integer :: id
   type(CropChoppedType) :: data
   end subroutine
   subroutine unpack_CropChopped(variant, data)
   IMPORT :: CropChoppedType
   ml_external unpack_CropChopped
!STDCALL(unpack_CropChopped)
   integer :: variant
   type(CropChoppedType) :: data
   end subroutine
   subroutine publish_Cultivate(id, data)
   IMPORT :: CultivateType
   ml_external publish_Cultivate
!STDCALL(publish_Cultivate)
   integer :: id
   type(CultivateType) :: data
   end subroutine
   subroutine unpack_Cultivate(variant, data)
   IMPORT :: CultivateType
   ml_external unpack_Cultivate
!STDCALL(unpack_Cultivate)
   integer :: variant
   type(CultivateType) :: data
   end subroutine
   subroutine publish_CanopyEnergyBalanceInterceptionlayer(id, data)
   IMPORT :: CanopyEnergyBalanceInterceptionlayerType
   ml_external publish_CanopyEnergyBalanceInterceptionlayer
!STDCALL(publish_CanopyEnergyBalanceInterceptionlayer)
   integer :: id
   type(CanopyEnergyBalanceInterceptionlayerType) :: data
   end subroutine
   subroutine unpack_CanopyEnergyBalanceInterceptionlayer(variant, data)
   IMPORT :: CanopyEnergyBalanceInterceptionlayerType
   ml_external unpack_CanopyEnergyBalanceInterceptionlayer
!STDCALL(unpack_CanopyEnergyBalanceInterceptionlayer)
   integer :: variant
   type(CanopyEnergyBalanceInterceptionlayerType) :: data
   end subroutine
   subroutine publish_CanopyEnergyBalanceInterception(id, data)
   IMPORT :: CanopyEnergyBalanceInterceptionType
   ml_external publish_CanopyEnergyBalanceInterception
!STDCALL(publish_CanopyEnergyBalanceInterception)
   integer :: id
   type(CanopyEnergyBalanceInterceptionType) :: data
   end subroutine
   subroutine unpack_CanopyEnergyBalanceInterception(variant, data)
   IMPORT :: CanopyEnergyBalanceInterceptionType
   ml_external unpack_CanopyEnergyBalanceInterception
!STDCALL(unpack_CanopyEnergyBalanceInterception)
   integer :: variant
   type(CanopyEnergyBalanceInterceptionType) :: data
   end subroutine
   subroutine publish_CanopyEnergyBalance(id, data)
   IMPORT :: CanopyEnergyBalanceType
   ml_external publish_CanopyEnergyBalance
!STDCALL(publish_CanopyEnergyBalance)
   integer :: id
   type(CanopyEnergyBalanceType) :: data
   end subroutine
   subroutine unpack_CanopyEnergyBalance(variant, data)
   IMPORT :: CanopyEnergyBalanceType
   ml_external unpack_CanopyEnergyBalance
!STDCALL(unpack_CanopyEnergyBalance)
   integer :: variant
   type(CanopyEnergyBalanceType) :: data
   end subroutine
   subroutine publish_CanopyWaterBalanceCanopy(id, data)
   IMPORT :: CanopyWaterBalanceCanopyType
   ml_external publish_CanopyWaterBalanceCanopy
!STDCALL(publish_CanopyWaterBalanceCanopy)
   integer :: id
   type(CanopyWaterBalanceCanopyType) :: data
   end subroutine
   subroutine unpack_CanopyWaterBalanceCanopy(variant, data)
   IMPORT :: CanopyWaterBalanceCanopyType
   ml_external unpack_CanopyWaterBalanceCanopy
!STDCALL(unpack_CanopyWaterBalanceCanopy)
   integer :: variant
   type(CanopyWaterBalanceCanopyType) :: data
   end subroutine
   subroutine publish_CanopyWaterBalance(id, data)
   IMPORT :: CanopyWaterBalanceType
   ml_external publish_CanopyWaterBalance
!STDCALL(publish_CanopyWaterBalance)
   integer :: id
   type(CanopyWaterBalanceType) :: data
   end subroutine
   subroutine unpack_CanopyWaterBalance(variant, data)
   IMPORT :: CanopyWaterBalanceType
   ml_external unpack_CanopyWaterBalance
!STDCALL(unpack_CanopyWaterBalance)
   integer :: variant
   type(CanopyWaterBalanceType) :: data
   end subroutine
   subroutine publish_CohortCanopyCanopyLayer(id, data)
   IMPORT :: CohortCanopyCanopyLayerType
   ml_external publish_CohortCanopyCanopyLayer
!STDCALL(publish_CohortCanopyCanopyLayer)
   integer :: id
   type(CohortCanopyCanopyLayerType) :: data
   end subroutine
   subroutine unpack_CohortCanopyCanopyLayer(variant, data)
   IMPORT :: CohortCanopyCanopyLayerType
   ml_external unpack_CohortCanopyCanopyLayer
!STDCALL(unpack_CohortCanopyCanopyLayer)
   integer :: variant
   type(CohortCanopyCanopyLayerType) :: data
   end subroutine
   subroutine publish_CohortCanopy(id, data)
   IMPORT :: CohortCanopyType
   ml_external publish_CohortCanopy
!STDCALL(publish_CohortCanopy)
   integer :: id
   type(CohortCanopyType) :: data
   end subroutine
   subroutine unpack_CohortCanopy(variant, data)
   IMPORT :: CohortCanopyType
   ml_external unpack_CohortCanopy
!STDCALL(unpack_CohortCanopy)
   integer :: variant
   type(CohortCanopyType) :: data
   end subroutine
   subroutine publish_CanopyArbitrationCanopyLayer(id, data)
   IMPORT :: CanopyArbitrationCanopyLayerType
   ml_external publish_CanopyArbitrationCanopyLayer
!STDCALL(publish_CanopyArbitrationCanopyLayer)
   integer :: id
   type(CanopyArbitrationCanopyLayerType) :: data
   end subroutine
   subroutine unpack_CanopyArbitrationCanopyLayer(variant, data)
   IMPORT :: CanopyArbitrationCanopyLayerType
   ml_external unpack_CanopyArbitrationCanopyLayer
!STDCALL(unpack_CanopyArbitrationCanopyLayer)
   integer :: variant
   type(CanopyArbitrationCanopyLayerType) :: data
   end subroutine
   subroutine publish_CanopyArbitration(id, data)
   IMPORT :: CanopyArbitrationType
   ml_external publish_CanopyArbitration
!STDCALL(publish_CanopyArbitration)
   integer :: id
   type(CanopyArbitrationType) :: data
   end subroutine
   subroutine unpack_CanopyArbitration(variant, data)
   IMPORT :: CanopyArbitrationType
   ml_external unpack_CanopyArbitration
!STDCALL(unpack_CanopyArbitration)
   integer :: variant
   type(CanopyArbitrationType) :: data
   end subroutine
   subroutine publish_IrrigationApplication(id, data)
   IMPORT :: IrrigationApplicationType
   ml_external publish_IrrigationApplication
!STDCALL(publish_IrrigationApplication)
   integer :: id
   type(IrrigationApplicationType) :: data
   end subroutine
   subroutine unpack_IrrigationApplication(variant, data)
   IMPORT :: IrrigationApplicationType
   ml_external unpack_IrrigationApplication
!STDCALL(unpack_IrrigationApplication)
   integer :: variant
   type(IrrigationApplicationType) :: data
   end subroutine
   subroutine publish_WaterChanged(id, data)
   IMPORT :: WaterChangedType
   ml_external publish_WaterChanged
!STDCALL(publish_WaterChanged)
   integer :: id
   type(WaterChangedType) :: data
   end subroutine
   subroutine unpack_WaterChanged(variant, data)
   IMPORT :: WaterChangedType
   ml_external unpack_WaterChanged
!STDCALL(unpack_WaterChanged)
   integer :: variant
   type(WaterChangedType) :: data
   end subroutine
   subroutine publish_WaterUptakesCalculatedUptakes(id, data)
   IMPORT :: WaterUptakesCalculatedUptakesType
   ml_external publish_WaterUptakesCalculatedUptakes
!STDCALL(publish_WaterUptakesCalculatedUptakes)
   integer :: id
   type(WaterUptakesCalculatedUptakesType) :: data
   end subroutine
   subroutine unpack_WaterUptakesCalculatedUptakes(variant, data)
   IMPORT :: WaterUptakesCalculatedUptakesType
   ml_external unpack_WaterUptakesCalculatedUptakes
!STDCALL(unpack_WaterUptakesCalculatedUptakes)
   integer :: variant
   type(WaterUptakesCalculatedUptakesType) :: data
   end subroutine
   subroutine publish_WaterUptakesCalculated(id, data)
   IMPORT :: WaterUptakesCalculatedType
   ml_external publish_WaterUptakesCalculated
!STDCALL(publish_WaterUptakesCalculated)
   integer :: id
   type(WaterUptakesCalculatedType) :: data
   end subroutine
   subroutine unpack_WaterUptakesCalculated(variant, data)
   IMPORT :: WaterUptakesCalculatedType
   ml_external unpack_WaterUptakesCalculated
!STDCALL(unpack_WaterUptakesCalculated)
   integer :: variant
   type(WaterUptakesCalculatedType) :: data
   end subroutine
   subroutine publish_NitrogenChanged(id, data)
   IMPORT :: NitrogenChangedType
   ml_external publish_NitrogenChanged
!STDCALL(publish_NitrogenChanged)
   integer :: id
   type(NitrogenChangedType) :: data
   end subroutine
   subroutine unpack_NitrogenChanged(variant, data)
   IMPORT :: NitrogenChangedType
   ml_external unpack_NitrogenChanged
!STDCALL(unpack_NitrogenChanged)
   integer :: variant
   type(NitrogenChangedType) :: data
   end subroutine
   subroutine publish_FOM(id, data)
   IMPORT :: FOMType
   ml_external publish_FOM
!STDCALL(publish_FOM)
   integer :: id
   type(FOMType) :: data
   end subroutine
   subroutine unpack_FOM(variant, data)
   IMPORT :: FOMType
   ml_external unpack_FOM
!STDCALL(unpack_FOM)
   integer :: variant
   type(FOMType) :: data
   end subroutine
   subroutine publish_FOMLayerLayer(id, data)
   IMPORT :: FOMLayerLayerType
   ml_external publish_FOMLayerLayer
!STDCALL(publish_FOMLayerLayer)
   integer :: id
   type(FOMLayerLayerType) :: data
   end subroutine
   subroutine unpack_FOMLayerLayer(variant, data)
   IMPORT :: FOMLayerLayerType
   ml_external unpack_FOMLayerLayer
!STDCALL(unpack_FOMLayerLayer)
   integer :: variant
   type(FOMLayerLayerType) :: data
   end subroutine
   subroutine publish_FOMLayer(id, data)
   IMPORT :: FOMLayerType
   ml_external publish_FOMLayer
!STDCALL(publish_FOMLayer)
   integer :: id
   type(FOMLayerType) :: data
   end subroutine
   subroutine unpack_FOMLayer(variant, data)
   IMPORT :: FOMLayerType
   ml_external unpack_FOMLayer
!STDCALL(unpack_FOMLayer)
   integer :: variant
   type(FOMLayerType) :: data
   end subroutine
   subroutine publish_FOMPoolLayer(id, data)
   IMPORT :: FOMPoolLayerType
   ml_external publish_FOMPoolLayer
!STDCALL(publish_FOMPoolLayer)
   integer :: id
   type(FOMPoolLayerType) :: data
   end subroutine
   subroutine unpack_FOMPoolLayer(variant, data)
   IMPORT :: FOMPoolLayerType
   ml_external unpack_FOMPoolLayer
!STDCALL(unpack_FOMPoolLayer)
   integer :: variant
   type(FOMPoolLayerType) :: data
   end subroutine
   subroutine publish_FOMPool(id, data)
   IMPORT :: FOMPoolType
   ml_external publish_FOMPool
!STDCALL(publish_FOMPool)
   integer :: id
   type(FOMPoolType) :: data
   end subroutine
   subroutine unpack_FOMPool(variant, data)
   IMPORT :: FOMPoolType
   ml_external unpack_FOMPool
!STDCALL(unpack_FOMPool)
   integer :: variant
   type(FOMPoolType) :: data
   end subroutine
   subroutine publish_SurfaceOrganicMatterPool(id, data)
   IMPORT :: SurfaceOrganicMatterPoolType
   ml_external publish_SurfaceOrganicMatterPool
!STDCALL(publish_SurfaceOrganicMatterPool)
   integer :: id
   type(SurfaceOrganicMatterPoolType) :: data
   end subroutine
   subroutine unpack_SurfaceOrganicMatterPool(variant, data)
   IMPORT :: SurfaceOrganicMatterPoolType
   ml_external unpack_SurfaceOrganicMatterPool
!STDCALL(unpack_SurfaceOrganicMatterPool)
   integer :: variant
   type(SurfaceOrganicMatterPoolType) :: data
   end subroutine
   subroutine publish_SurfaceOrganicMatter(id, data)
   IMPORT :: SurfaceOrganicMatterType
   ml_external publish_SurfaceOrganicMatter
!STDCALL(publish_SurfaceOrganicMatter)
   integer :: id
   type(SurfaceOrganicMatterType) :: data
   end subroutine
   subroutine unpack_SurfaceOrganicMatter(variant, data)
   IMPORT :: SurfaceOrganicMatterType
   ml_external unpack_SurfaceOrganicMatter
!STDCALL(unpack_SurfaceOrganicMatter)
   integer :: variant
   type(SurfaceOrganicMatterType) :: data
   end subroutine
   subroutine publish_SurfaceOrganicMatterDecompPool(id, data)
   IMPORT :: SurfaceOrganicMatterDecompPoolType
   ml_external publish_SurfaceOrganicMatterDecompPool
!STDCALL(publish_SurfaceOrganicMatterDecompPool)
   integer :: id
   type(SurfaceOrganicMatterDecompPoolType) :: data
   end subroutine
   subroutine unpack_SurfaceOrganicMatterDecompPool(variant, data)
   IMPORT :: SurfaceOrganicMatterDecompPoolType
   ml_external unpack_SurfaceOrganicMatterDecompPool
!STDCALL(unpack_SurfaceOrganicMatterDecompPool)
   integer :: variant
   type(SurfaceOrganicMatterDecompPoolType) :: data
   end subroutine
   subroutine publish_SurfaceOrganicMatterDecomp(id, data)
   IMPORT :: SurfaceOrganicMatterDecompType
   ml_external publish_SurfaceOrganicMatterDecomp
!STDCALL(publish_SurfaceOrganicMatterDecomp)
   integer :: id
   type(SurfaceOrganicMatterDecompType) :: data
   end subroutine
   subroutine unpack_SurfaceOrganicMatterDecomp(variant, data)
   IMPORT :: SurfaceOrganicMatterDecompType
   ml_external unpack_SurfaceOrganicMatterDecomp
!STDCALL(unpack_SurfaceOrganicMatterDecomp)
   integer :: variant
   type(SurfaceOrganicMatterDecompType) :: data
   end subroutine
   subroutine publish_SoilOrganicMatterlayer(id, data)
   IMPORT :: SoilOrganicMatterlayerType
   ml_external publish_SoilOrganicMatterlayer
!STDCALL(publish_SoilOrganicMatterlayer)
   integer :: id
   type(SoilOrganicMatterlayerType) :: data
   end subroutine
   subroutine unpack_SoilOrganicMatterlayer(variant, data)
   IMPORT :: SoilOrganicMatterlayerType
   ml_external unpack_SoilOrganicMatterlayer
!STDCALL(unpack_SoilOrganicMatterlayer)
   integer :: variant
   type(SoilOrganicMatterlayerType) :: data
   end subroutine
   subroutine publish_SoilOrganicMatter(id, data)
   IMPORT :: SoilOrganicMatterType
   ml_external publish_SoilOrganicMatter
!STDCALL(publish_SoilOrganicMatter)
   integer :: id
   type(SoilOrganicMatterType) :: data
   end subroutine
   subroutine unpack_SoilOrganicMatter(variant, data)
   IMPORT :: SoilOrganicMatterType
   ml_external unpack_SoilOrganicMatter
!STDCALL(unpack_SoilOrganicMatter)
   integer :: variant
   type(SoilOrganicMatterType) :: data
   end subroutine
   subroutine publish_IncorpFom(id, data)
   IMPORT :: IncorpFomType
   ml_external publish_IncorpFom
!STDCALL(publish_IncorpFom)
   integer :: id
   type(IncorpFomType) :: data
   end subroutine
   subroutine unpack_IncorpFom(variant, data)
   IMPORT :: IncorpFomType
   ml_external unpack_IncorpFom
!STDCALL(unpack_IncorpFom)
   integer :: variant
   type(IncorpFomType) :: data
   end subroutine
   subroutine publish_Residue_removed(id, data)
   IMPORT :: Residue_removedType
   ml_external publish_Residue_removed
!STDCALL(publish_Residue_removed)
   integer :: id
   type(Residue_removedType) :: data
   end subroutine
   subroutine unpack_Residue_removed(variant, data)
   IMPORT :: Residue_removedType
   ml_external unpack_Residue_removed
!STDCALL(unpack_Residue_removed)
   integer :: variant
   type(Residue_removedType) :: data
   end subroutine
   subroutine publish_Residue_added(id, data)
   IMPORT :: Residue_addedType
   ml_external publish_Residue_added
!STDCALL(publish_Residue_added)
   integer :: id
   type(Residue_addedType) :: data
   end subroutine
   subroutine unpack_Residue_added(variant, data)
   IMPORT :: Residue_addedType
   ml_external unpack_Residue_added
!STDCALL(unpack_Residue_added)
   integer :: variant
   type(Residue_addedType) :: data
   end subroutine
   subroutine publish_SurfaceOM_removed(id, data)
   IMPORT :: SurfaceOM_removedType
   ml_external publish_SurfaceOM_removed
!STDCALL(publish_SurfaceOM_removed)
   integer :: id
   type(SurfaceOM_removedType) :: data
   end subroutine
   subroutine unpack_SurfaceOM_removed(variant, data)
   IMPORT :: SurfaceOM_removedType
   ml_external unpack_SurfaceOM_removed
!STDCALL(unpack_SurfaceOM_removed)
   integer :: variant
   type(SurfaceOM_removedType) :: data
   end subroutine
   subroutine publish_Tillage(id, data)
   IMPORT :: TillageType
   ml_external publish_Tillage
!STDCALL(publish_Tillage)
   integer :: id
   type(TillageType) :: data
   end subroutine
   subroutine unpack_Tillage(variant, data)
   IMPORT :: TillageType
   ml_external unpack_Tillage
!STDCALL(unpack_Tillage)
   integer :: variant
   type(TillageType) :: data
   end subroutine
   subroutine publish_Add_surfaceom(id, data)
   IMPORT :: Add_surfaceomType
   ml_external publish_Add_surfaceom
!STDCALL(publish_Add_surfaceom)
   integer :: id
   type(Add_surfaceomType) :: data
   end subroutine
   subroutine unpack_Add_surfaceom(variant, data)
   IMPORT :: Add_surfaceomType
   ml_external unpack_Add_surfaceom
!STDCALL(unpack_Add_surfaceom)
   integer :: variant
   type(Add_surfaceomType) :: data
   end subroutine
   subroutine publish_BiomassRemoved(id, data)
   IMPORT :: BiomassRemovedType
   ml_external publish_BiomassRemoved
!STDCALL(publish_BiomassRemoved)
   integer :: id
   type(BiomassRemovedType) :: data
   end subroutine
   subroutine unpack_BiomassRemoved(variant, data)
   IMPORT :: BiomassRemovedType
   ml_external unpack_BiomassRemoved
!STDCALL(unpack_BiomassRemoved)
   integer :: variant
   type(BiomassRemovedType) :: data
   end subroutine
   subroutine publish_NewProfile(id, data)
   IMPORT :: NewProfileType
   ml_external publish_NewProfile
!STDCALL(publish_NewProfile)
   integer :: id
   type(NewProfileType) :: data
   end subroutine
   subroutine unpack_NewProfile(variant, data)
   IMPORT :: NewProfileType
   ml_external unpack_NewProfile
!STDCALL(unpack_NewProfile)
   integer :: variant
   type(NewProfileType) :: data
   end subroutine
   subroutine publish_NewPotentialGrowth(id, data)
   IMPORT :: NewPotentialGrowthType
   ml_external publish_NewPotentialGrowth
!STDCALL(publish_NewPotentialGrowth)
   integer :: id
   type(NewPotentialGrowthType) :: data
   end subroutine
   subroutine unpack_NewPotentialGrowth(variant, data)
   IMPORT :: NewPotentialGrowthType
   ml_external unpack_NewPotentialGrowth
!STDCALL(unpack_NewPotentialGrowth)
   integer :: variant
   type(NewPotentialGrowthType) :: data
   end subroutine
   subroutine publish_NewCanopy(id, data)
   IMPORT :: NewCanopyType
   ml_external publish_NewCanopy
!STDCALL(publish_NewCanopy)
   integer :: id
   type(NewCanopyType) :: data
   end subroutine
   subroutine unpack_NewCanopy(variant, data)
   IMPORT :: NewCanopyType
   ml_external unpack_NewCanopy
!STDCALL(unpack_NewCanopy)
   integer :: variant
   type(NewCanopyType) :: data
   end subroutine
   subroutine publish_NewCrop(id, data)
   IMPORT :: NewCropType
   ml_external publish_NewCrop
!STDCALL(publish_NewCrop)
   integer :: id
   type(NewCropType) :: data
   end subroutine
   subroutine unpack_NewCrop(variant, data)
   IMPORT :: NewCropType
   ml_external unpack_NewCrop
!STDCALL(unpack_NewCrop)
   integer :: variant
   type(NewCropType) :: data
   end subroutine
   subroutine publish_Graze(id, data)
   IMPORT :: GrazeType
   ml_external publish_Graze
!STDCALL(publish_Graze)
   integer :: id
   type(GrazeType) :: data
   end subroutine
   subroutine unpack_Graze(variant, data)
   IMPORT :: GrazeType
   ml_external unpack_Graze
!STDCALL(unpack_Graze)
   integer :: variant
   type(GrazeType) :: data
   end subroutine
   subroutine publish_AnimalGraze(id, data)
   IMPORT :: AnimalGrazeType
   ml_external publish_AnimalGraze
!STDCALL(publish_AnimalGraze)
   integer :: id
   type(AnimalGrazeType) :: data
   end subroutine
   subroutine unpack_AnimalGraze(variant, data)
   IMPORT :: AnimalGrazeType
   ml_external unpack_AnimalGraze
!STDCALL(unpack_AnimalGraze)
   integer :: variant
   type(AnimalGrazeType) :: data
   end subroutine
   subroutine publish_FomAddedfom(id, data)
   IMPORT :: FomAddedfomType
   ml_external publish_FomAddedfom
!STDCALL(publish_FomAddedfom)
   integer :: id
   type(FomAddedfomType) :: data
   end subroutine
   subroutine unpack_FomAddedfom(variant, data)
   IMPORT :: FomAddedfomType
   ml_external unpack_FomAddedfom
!STDCALL(unpack_FomAddedfom)
   integer :: variant
   type(FomAddedfomType) :: data
   end subroutine
   subroutine publish_FomAdded(id, data)
   IMPORT :: FomAddedType
   ml_external publish_FomAdded
!STDCALL(publish_FomAdded)
   integer :: id
   type(FomAddedType) :: data
   end subroutine
   subroutine unpack_FomAdded(variant, data)
   IMPORT :: FomAddedType
   ml_external unpack_FomAdded
!STDCALL(unpack_FomAdded)
   integer :: variant
   type(FomAddedType) :: data
   end subroutine
   subroutine publish_PastureSow(id, data)
   IMPORT :: PastureSowType
   ml_external publish_PastureSow
!STDCALL(publish_PastureSow)
   integer :: id
   type(PastureSowType) :: data
   end subroutine
   subroutine unpack_PastureSow(variant, data)
   IMPORT :: PastureSowType
   ml_external unpack_PastureSow
!STDCALL(unpack_PastureSow)
   integer :: variant
   type(PastureSowType) :: data
   end subroutine
   subroutine publish_Kill(id, data)
   IMPORT :: KillType
   ml_external publish_Kill
!STDCALL(publish_Kill)
   integer :: id
   type(KillType) :: data
   end subroutine
   subroutine unpack_Kill(variant, data)
   IMPORT :: KillType
   ml_external unpack_Kill
!STDCALL(unpack_Kill)
   integer :: variant
   type(KillType) :: data
   end subroutine
   subroutine publish_PastureCultivate(id, data)
   IMPORT :: PastureCultivateType
   ml_external publish_PastureCultivate
!STDCALL(publish_PastureCultivate)
   integer :: id
   type(PastureCultivateType) :: data
   end subroutine
   subroutine unpack_PastureCultivate(variant, data)
   IMPORT :: PastureCultivateType
   ml_external unpack_PastureCultivate
!STDCALL(unpack_PastureCultivate)
   integer :: variant
   type(PastureCultivateType) :: data
   end subroutine
   subroutine publish_Cut(id, data)
   IMPORT :: CutType
   ml_external publish_Cut
!STDCALL(publish_Cut)
   integer :: id
   type(CutType) :: data
   end subroutine
   subroutine unpack_Cut(variant, data)
   IMPORT :: CutType
   ml_external unpack_Cut
!STDCALL(unpack_Cut)
   integer :: variant
   type(CutType) :: data
   end subroutine
   subroutine publish_Burn(id, data)
   IMPORT :: BurnType
   ml_external publish_Burn
!STDCALL(publish_Burn)
   integer :: id
   type(BurnType) :: data
   end subroutine
   subroutine unpack_Burn(variant, data)
   IMPORT :: BurnType
   ml_external unpack_Burn
!STDCALL(unpack_Burn)
   integer :: variant
   type(BurnType) :: data
   end subroutine
   subroutine publish_PastureOnCut(id, data)
   IMPORT :: PastureOnCutType
   ml_external publish_PastureOnCut
!STDCALL(publish_PastureOnCut)
   integer :: id
   type(PastureOnCutType) :: data
   end subroutine
   subroutine unpack_PastureOnCut(variant, data)
   IMPORT :: PastureOnCutType
   ml_external unpack_PastureOnCut
!STDCALL(unpack_PastureOnCut)
   integer :: variant
   type(PastureOnCutType) :: data
   end subroutine
   subroutine publish_FaecesPool(id, data)
   IMPORT :: FaecesPoolType
   ml_external publish_FaecesPool
!STDCALL(publish_FaecesPool)
   integer :: id
   type(FaecesPoolType) :: data
   end subroutine
   subroutine unpack_FaecesPool(variant, data)
   IMPORT :: FaecesPoolType
   ml_external unpack_FaecesPool
!STDCALL(unpack_FaecesPool)
   integer :: variant
   type(FaecesPoolType) :: data
   end subroutine
   subroutine publish_Faeces(id, data)
   IMPORT :: FaecesType
   ml_external publish_Faeces
!STDCALL(publish_Faeces)
   integer :: id
   type(FaecesType) :: data
   end subroutine
   subroutine unpack_Faeces(variant, data)
   IMPORT :: FaecesType
   ml_external unpack_Faeces
!STDCALL(unpack_Faeces)
   integer :: variant
   type(FaecesType) :: data
   end subroutine
   subroutine publish_FaecesInorgPool(id, data)
   IMPORT :: FaecesInorgPoolType
   ml_external publish_FaecesInorgPool
!STDCALL(publish_FaecesInorgPool)
   integer :: id
   type(FaecesInorgPoolType) :: data
   end subroutine
   subroutine unpack_FaecesInorgPool(variant, data)
   IMPORT :: FaecesInorgPoolType
   ml_external unpack_FaecesInorgPool
!STDCALL(unpack_FaecesInorgPool)
   integer :: variant
   type(FaecesInorgPoolType) :: data
   end subroutine
   subroutine publish_FaecesInorg(id, data)
   IMPORT :: FaecesInorgType
   ml_external publish_FaecesInorg
!STDCALL(publish_FaecesInorg)
   integer :: id
   type(FaecesInorgType) :: data
   end subroutine
   subroutine unpack_FaecesInorg(variant, data)
   IMPORT :: FaecesInorgType
   ml_external unpack_FaecesInorg
!STDCALL(unpack_FaecesInorg)
   integer :: variant
   type(FaecesInorgType) :: data
   end subroutine
   subroutine publish_IntakePool(id, data)
   IMPORT :: IntakePoolType
   ml_external publish_IntakePool
!STDCALL(publish_IntakePool)
   integer :: id
   type(IntakePoolType) :: data
   end subroutine
   subroutine unpack_IntakePool(variant, data)
   IMPORT :: IntakePoolType
   ml_external unpack_IntakePool
!STDCALL(unpack_IntakePool)
   integer :: variant
   type(IntakePoolType) :: data
   end subroutine
   subroutine publish_Intake(id, data)
   IMPORT :: IntakeType
   ml_external publish_Intake
!STDCALL(publish_Intake)
   integer :: id
   type(IntakeType) :: data
   end subroutine
   subroutine unpack_Intake(variant, data)
   IMPORT :: IntakeType
   ml_external unpack_Intake
!STDCALL(unpack_Intake)
   integer :: variant
   type(IntakeType) :: data
   end subroutine
   subroutine publish_PastIntakePool(id, data)
   IMPORT :: PastIntakePoolType
   ml_external publish_PastIntakePool
!STDCALL(publish_PastIntakePool)
   integer :: id
   type(PastIntakePoolType) :: data
   end subroutine
   subroutine unpack_PastIntakePool(variant, data)
   IMPORT :: PastIntakePoolType
   ml_external unpack_PastIntakePool
!STDCALL(unpack_PastIntakePool)
   integer :: variant
   type(PastIntakePoolType) :: data
   end subroutine
   subroutine publish_PastIntake(id, data)
   IMPORT :: PastIntakeType
   ml_external publish_PastIntake
!STDCALL(publish_PastIntake)
   integer :: id
   type(PastIntakeType) :: data
   end subroutine
   subroutine unpack_PastIntake(variant, data)
   IMPORT :: PastIntakeType
   ml_external unpack_PastIntake
!STDCALL(unpack_PastIntake)
   integer :: variant
   type(PastIntakeType) :: data
   end subroutine
   subroutine publish_SuppIntakePool(id, data)
   IMPORT :: SuppIntakePoolType
   ml_external publish_SuppIntakePool
!STDCALL(publish_SuppIntakePool)
   integer :: id
   type(SuppIntakePoolType) :: data
   end subroutine
   subroutine unpack_SuppIntakePool(variant, data)
   IMPORT :: SuppIntakePoolType
   ml_external unpack_SuppIntakePool
!STDCALL(unpack_SuppIntakePool)
   integer :: variant
   type(SuppIntakePoolType) :: data
   end subroutine
   subroutine publish_SuppIntake(id, data)
   IMPORT :: SuppIntakeType
   ml_external publish_SuppIntake
!STDCALL(publish_SuppIntake)
   integer :: id
   type(SuppIntakeType) :: data
   end subroutine
   subroutine unpack_SuppIntake(variant, data)
   IMPORT :: SuppIntakeType
   ml_external unpack_SuppIntake
!STDCALL(unpack_SuppIntake)
   integer :: variant
   type(SuppIntakeType) :: data
   end subroutine
   subroutine publish_AddExcretafaeces_om(id, data)
   IMPORT :: AddExcretafaeces_omType
   ml_external publish_AddExcretafaeces_om
!STDCALL(publish_AddExcretafaeces_om)
   integer :: id
   type(AddExcretafaeces_omType) :: data
   end subroutine
   subroutine unpack_AddExcretafaeces_om(variant, data)
   IMPORT :: AddExcretafaeces_omType
   ml_external unpack_AddExcretafaeces_om
!STDCALL(unpack_AddExcretafaeces_om)
   integer :: variant
   type(AddExcretafaeces_omType) :: data
   end subroutine
   subroutine publish_AddExcretafaeces_inorg(id, data)
   IMPORT :: AddExcretafaeces_inorgType
   ml_external publish_AddExcretafaeces_inorg
!STDCALL(publish_AddExcretafaeces_inorg)
   integer :: id
   type(AddExcretafaeces_inorgType) :: data
   end subroutine
   subroutine unpack_AddExcretafaeces_inorg(variant, data)
   IMPORT :: AddExcretafaeces_inorgType
   ml_external unpack_AddExcretafaeces_inorg
!STDCALL(unpack_AddExcretafaeces_inorg)
   integer :: variant
   type(AddExcretafaeces_inorgType) :: data
   end subroutine
   subroutine publish_AddExcretaurine(id, data)
   IMPORT :: AddExcretaurineType
   ml_external publish_AddExcretaurine
!STDCALL(publish_AddExcretaurine)
   integer :: id
   type(AddExcretaurineType) :: data
   end subroutine
   subroutine unpack_AddExcretaurine(variant, data)
   IMPORT :: AddExcretaurineType
   ml_external unpack_AddExcretaurine
!STDCALL(unpack_AddExcretaurine)
   integer :: variant
   type(AddExcretaurineType) :: data
   end subroutine
   subroutine publish_AddExcreta(id, data)
   IMPORT :: AddExcretaType
   ml_external publish_AddExcreta
!STDCALL(publish_AddExcreta)
   integer :: id
   type(AddExcretaType) :: data
   end subroutine
   subroutine unpack_AddExcreta(variant, data)
   IMPORT :: AddExcretaType
   ml_external unpack_AddExcreta
!STDCALL(unpack_AddExcreta)
   integer :: variant
   type(AddExcretaType) :: data
   end subroutine
   subroutine publish_RemoveHerbage(id, data)
   IMPORT :: RemoveHerbageType
   ml_external publish_RemoveHerbage
!STDCALL(publish_RemoveHerbage)
   integer :: id
   type(RemoveHerbageType) :: data
   end subroutine
   subroutine unpack_RemoveHerbage(variant, data)
   IMPORT :: RemoveHerbageType
   ml_external unpack_RemoveHerbage
!STDCALL(unpack_RemoveHerbage)
   integer :: variant
   type(RemoveHerbageType) :: data
   end subroutine
   subroutine publish_AddResidue(id, data)
   IMPORT :: AddResidueType
   ml_external publish_AddResidue
!STDCALL(publish_AddResidue)
   integer :: id
   type(AddResidueType) :: data
   end subroutine
   subroutine unpack_AddResidue(variant, data)
   IMPORT :: AddResidueType
   ml_external unpack_AddResidue
!STDCALL(unpack_AddResidue)
   integer :: variant
   type(AddResidueType) :: data
   end subroutine
   subroutine publish_SuppEatenPool(id, data)
   IMPORT :: SuppEatenPoolType
   ml_external publish_SuppEatenPool
!STDCALL(publish_SuppEatenPool)
   integer :: id
   type(SuppEatenPoolType) :: data
   end subroutine
   subroutine unpack_SuppEatenPool(variant, data)
   IMPORT :: SuppEatenPoolType
   ml_external unpack_SuppEatenPool
!STDCALL(unpack_SuppEatenPool)
   integer :: variant
   type(SuppEatenPoolType) :: data
   end subroutine
   subroutine publish_SuppEaten(id, data)
   IMPORT :: SuppEatenType
   ml_external publish_SuppEaten
!STDCALL(publish_SuppEaten)
   integer :: id
   type(SuppEatenType) :: data
   end subroutine
   subroutine unpack_SuppEaten(variant, data)
   IMPORT :: SuppEatenType
   ml_external unpack_SuppEaten
!STDCALL(unpack_SuppEaten)
   integer :: variant
   type(SuppEatenType) :: data
   end subroutine
   subroutine publish_Plant2Stockherbage(id, data)
   IMPORT :: Plant2StockherbageType
   ml_external publish_Plant2Stockherbage
!STDCALL(publish_Plant2Stockherbage)
   integer :: id
   type(Plant2StockherbageType) :: data
   end subroutine
   subroutine unpack_Plant2Stockherbage(variant, data)
   IMPORT :: Plant2StockherbageType
   ml_external unpack_Plant2Stockherbage
!STDCALL(unpack_Plant2Stockherbage)
   integer :: variant
   type(Plant2StockherbageType) :: data
   end subroutine
   subroutine publish_Plant2Stockseed(id, data)
   IMPORT :: Plant2StockseedType
   ml_external publish_Plant2Stockseed
!STDCALL(publish_Plant2Stockseed)
   integer :: id
   type(Plant2StockseedType) :: data
   end subroutine
   subroutine unpack_Plant2Stockseed(variant, data)
   IMPORT :: Plant2StockseedType
   ml_external unpack_Plant2Stockseed
!STDCALL(unpack_Plant2Stockseed)
   integer :: variant
   type(Plant2StockseedType) :: data
   end subroutine
   subroutine publish_Plant2Stock(id, data)
   IMPORT :: Plant2StockType
   ml_external publish_Plant2Stock
!STDCALL(publish_Plant2Stock)
   integer :: id
   type(Plant2StockType) :: data
   end subroutine
   subroutine unpack_Plant2Stock(variant, data)
   IMPORT :: Plant2StockType
   ml_external unpack_Plant2Stock
!STDCALL(unpack_Plant2Stock)
   integer :: variant
   type(Plant2StockType) :: data
   end subroutine
   subroutine publish_Prioritise(id, data)
   IMPORT :: PrioritiseType
   ml_external publish_Prioritise
!STDCALL(publish_Prioritise)
   integer :: id
   type(PrioritiseType) :: data
   end subroutine
   subroutine unpack_Prioritise(variant, data)
   IMPORT :: PrioritiseType
   ml_external unpack_Prioritise
!STDCALL(unpack_Prioritise)
   integer :: variant
   type(PrioritiseType) :: data
   end subroutine
   subroutine publish_AddAnimals(id, data)
   IMPORT :: AddAnimalsType
   ml_external publish_AddAnimals
!STDCALL(publish_AddAnimals)
   integer :: id
   type(AddAnimalsType) :: data
   end subroutine
   subroutine unpack_AddAnimals(variant, data)
   IMPORT :: AddAnimalsType
   ml_external unpack_AddAnimals
!STDCALL(unpack_AddAnimals)
   integer :: variant
   type(AddAnimalsType) :: data
   end subroutine
   subroutine publish_Buy(id, data)
   IMPORT :: BuyType
   ml_external publish_Buy
!STDCALL(publish_Buy)
   integer :: id
   type(BuyType) :: data
   end subroutine
   subroutine unpack_Buy(variant, data)
   IMPORT :: BuyType
   ml_external unpack_Buy
!STDCALL(unpack_Buy)
   integer :: variant
   type(BuyType) :: data
   end subroutine
   subroutine publish_Sell(id, data)
   IMPORT :: SellType
   ml_external publish_Sell
!STDCALL(publish_Sell)
   integer :: id
   type(SellType) :: data
   end subroutine
   subroutine unpack_Sell(variant, data)
   IMPORT :: SellType
   ml_external unpack_Sell
!STDCALL(unpack_Sell)
   integer :: variant
   type(SellType) :: data
   end subroutine
   subroutine publish_SellTag(id, data)
   IMPORT :: SellTagType
   ml_external publish_SellTag
!STDCALL(publish_SellTag)
   integer :: id
   type(SellTagType) :: data
   end subroutine
   subroutine unpack_SellTag(variant, data)
   IMPORT :: SellTagType
   ml_external unpack_SellTag
!STDCALL(unpack_SellTag)
   integer :: variant
   type(SellTagType) :: data
   end subroutine
   subroutine publish_Castrate(id, data)
   IMPORT :: CastrateType
   ml_external publish_Castrate
!STDCALL(publish_Castrate)
   integer :: id
   type(CastrateType) :: data
   end subroutine
   subroutine unpack_Castrate(variant, data)
   IMPORT :: CastrateType
   ml_external unpack_Castrate
!STDCALL(unpack_Castrate)
   integer :: variant
   type(CastrateType) :: data
   end subroutine
   subroutine publish_Dryoff(id, data)
   IMPORT :: DryoffType
   ml_external publish_Dryoff
!STDCALL(publish_Dryoff)
   integer :: id
   type(DryoffType) :: data
   end subroutine
   subroutine unpack_Dryoff(variant, data)
   IMPORT :: DryoffType
   ml_external unpack_Dryoff
!STDCALL(unpack_Dryoff)
   integer :: variant
   type(DryoffType) :: data
   end subroutine
   subroutine publish_Draft(id, data)
   IMPORT :: DraftType
   ml_external publish_Draft
!STDCALL(publish_Draft)
   integer :: id
   type(DraftType) :: data
   end subroutine
   subroutine unpack_Draft(variant, data)
   IMPORT :: DraftType
   ml_external unpack_Draft
!STDCALL(unpack_Draft)
   integer :: variant
   type(DraftType) :: data
   end subroutine
   subroutine publish_Join(id, data)
   IMPORT :: JoinType
   ml_external publish_Join
!STDCALL(publish_Join)
   integer :: id
   type(JoinType) :: data
   end subroutine
   subroutine unpack_Join(variant, data)
   IMPORT :: JoinType
   ml_external unpack_Join
!STDCALL(unpack_Join)
   integer :: variant
   type(JoinType) :: data
   end subroutine
   subroutine publish_Move(id, data)
   IMPORT :: MoveType
   ml_external publish_Move
!STDCALL(publish_Move)
   integer :: id
   type(MoveType) :: data
   end subroutine
   subroutine unpack_Move(variant, data)
   IMPORT :: MoveType
   ml_external unpack_Move
!STDCALL(unpack_Move)
   integer :: variant
   type(MoveType) :: data
   end subroutine
   subroutine publish_Shear(id, data)
   IMPORT :: ShearType
   ml_external publish_Shear
!STDCALL(publish_Shear)
   integer :: id
   type(ShearType) :: data
   end subroutine
   subroutine unpack_Shear(variant, data)
   IMPORT :: ShearType
   ml_external unpack_Shear
!STDCALL(unpack_Shear)
   integer :: variant
   type(ShearType) :: data
   end subroutine
   subroutine publish_Split(id, data)
   IMPORT :: SplitType
   ml_external publish_Split
!STDCALL(publish_Split)
   integer :: id
   type(SplitType) :: data
   end subroutine
   subroutine unpack_Split(variant, data)
   IMPORT :: SplitType
   ml_external unpack_Split
!STDCALL(unpack_Split)
   integer :: variant
   type(SplitType) :: data
   end subroutine
   subroutine publish_SplitAll(id, data)
   IMPORT :: SplitAllType
   ml_external publish_SplitAll
!STDCALL(publish_SplitAll)
   integer :: id
   type(SplitAllType) :: data
   end subroutine
   subroutine unpack_SplitAll(variant, data)
   IMPORT :: SplitAllType
   ml_external unpack_SplitAll
!STDCALL(unpack_SplitAll)
   integer :: variant
   type(SplitAllType) :: data
   end subroutine
   subroutine publish_Tag(id, data)
   IMPORT :: TagType
   ml_external publish_Tag
!STDCALL(publish_Tag)
   integer :: id
   type(TagType) :: data
   end subroutine
   subroutine unpack_Tag(variant, data)
   IMPORT :: TagType
   ml_external unpack_Tag
!STDCALL(unpack_Tag)
   integer :: variant
   type(TagType) :: data
   end subroutine
   subroutine publish_Wean(id, data)
   IMPORT :: WeanType
   ml_external publish_Wean
!STDCALL(publish_Wean)
   integer :: id
   type(WeanType) :: data
   end subroutine
   subroutine unpack_Wean(variant, data)
   IMPORT :: WeanType
   ml_external unpack_Wean
!STDCALL(unpack_Wean)
   integer :: variant
   type(WeanType) :: data
   end subroutine
   subroutine publish_RemoveCropBiomassdm(id, data)
   IMPORT :: RemoveCropBiomassdmType
   ml_external publish_RemoveCropBiomassdm
!STDCALL(publish_RemoveCropBiomassdm)
   integer :: id
   type(RemoveCropBiomassdmType) :: data
   end subroutine
   subroutine unpack_RemoveCropBiomassdm(variant, data)
   IMPORT :: RemoveCropBiomassdmType
   ml_external unpack_RemoveCropBiomassdm
!STDCALL(unpack_RemoveCropBiomassdm)
   integer :: variant
   type(RemoveCropBiomassdmType) :: data
   end subroutine
   subroutine publish_RemoveCropBiomass(id, data)
   IMPORT :: RemoveCropBiomassType
   ml_external publish_RemoveCropBiomass
!STDCALL(publish_RemoveCropBiomass)
   integer :: id
   type(RemoveCropBiomassType) :: data
   end subroutine
   subroutine unpack_RemoveCropBiomass(variant, data)
   IMPORT :: RemoveCropBiomassType
   ml_external unpack_RemoveCropBiomass
!STDCALL(unpack_RemoveCropBiomass)
   integer :: variant
   type(RemoveCropBiomassType) :: data
   end subroutine
   subroutine publish_RemoveResidueDm(id, data)
   IMPORT :: RemoveResidueDmType
   ml_external publish_RemoveResidueDm
!STDCALL(publish_RemoveResidueDm)
   integer :: id
   type(RemoveResidueDmType) :: data
   end subroutine
   subroutine unpack_RemoveResidueDm(variant, data)
   IMPORT :: RemoveResidueDmType
   ml_external unpack_RemoveResidueDm
!STDCALL(unpack_RemoveResidueDm)
   integer :: variant
   type(RemoveResidueDmType) :: data
   end subroutine
   subroutine publish_AddUrine(id, data)
   IMPORT :: AddUrineType
   ml_external publish_AddUrine
!STDCALL(publish_AddUrine)
   integer :: id
   type(AddUrineType) :: data
   end subroutine
   subroutine unpack_AddUrine(variant, data)
   IMPORT :: AddUrineType
   ml_external unpack_AddUrine
!STDCALL(unpack_AddUrine)
   integer :: variant
   type(AddUrineType) :: data
   end subroutine
   subroutine publish_AddFaeces(id, data)
   IMPORT :: AddFaecesType
   ml_external publish_AddFaeces
!STDCALL(publish_AddFaeces)
   integer :: id
   type(AddFaecesType) :: data
   end subroutine
   subroutine unpack_AddFaeces(variant, data)
   IMPORT :: AddFaecesType
   ml_external unpack_AddFaeces
!STDCALL(unpack_AddFaeces)
   integer :: variant
   type(AddFaecesType) :: data
   end subroutine
   subroutine publish_UrineExcreted(id, data)
   IMPORT :: UrineExcretedType
   ml_external publish_UrineExcreted
!STDCALL(publish_UrineExcreted)
   integer :: id
   type(UrineExcretedType) :: data
   end subroutine
   subroutine unpack_UrineExcreted(variant, data)
   IMPORT :: UrineExcretedType
   ml_external unpack_UrineExcreted
!STDCALL(unpack_UrineExcreted)
   integer :: variant
   type(UrineExcretedType) :: data
   end subroutine
   subroutine publish_FaecesExcreted(id, data)
   IMPORT :: FaecesExcretedType
   ml_external publish_FaecesExcreted
!STDCALL(publish_FaecesExcreted)
   integer :: id
   type(FaecesExcretedType) :: data
   end subroutine
   subroutine unpack_FaecesExcreted(variant, data)
   IMPORT :: FaecesExcretedType
   ml_external unpack_FaecesExcreted
!STDCALL(unpack_FaecesExcreted)
   integer :: variant
   type(FaecesExcretedType) :: data
   end subroutine
   subroutine publish_ApplyUrine(id, data)
   IMPORT :: ApplyUrineType
   ml_external publish_ApplyUrine
!STDCALL(publish_ApplyUrine)
   integer :: id
   type(ApplyUrineType) :: data
   end subroutine
   subroutine unpack_ApplyUrine(variant, data)
   IMPORT :: ApplyUrineType
   ml_external unpack_ApplyUrine
!STDCALL(unpack_ApplyUrine)
   integer :: variant
   type(ApplyUrineType) :: data
   end subroutine
   subroutine publish_SoilOrganicMaterial(id, data)
   IMPORT :: SoilOrganicMaterialType
   ml_external publish_SoilOrganicMaterial
!STDCALL(publish_SoilOrganicMaterial)
   integer :: id
   type(SoilOrganicMaterialType) :: data
   end subroutine
   subroutine unpack_SoilOrganicMaterial(variant, data)
   IMPORT :: SoilOrganicMaterialType
   ml_external unpack_SoilOrganicMaterial
!STDCALL(unpack_SoilOrganicMaterial)
   integer :: variant
   type(SoilOrganicMaterialType) :: data
   end subroutine
   subroutine publish_AddSoilCNPatch(id, data)
   IMPORT :: AddSoilCNPatchType
   ml_external publish_AddSoilCNPatch
!STDCALL(publish_AddSoilCNPatch)
   integer :: id
   type(AddSoilCNPatchType) :: data
   end subroutine
   subroutine unpack_AddSoilCNPatch(variant, data)
   IMPORT :: AddSoilCNPatchType
   ml_external unpack_AddSoilCNPatch
!STDCALL(unpack_AddSoilCNPatch)
   integer :: variant
   type(AddSoilCNPatchType) :: data
   end subroutine
   subroutine publish_AddSoilCNPatchwithFOMFOM(id, data)
   IMPORT :: AddSoilCNPatchwithFOMFOMType
   ml_external publish_AddSoilCNPatchwithFOMFOM
!STDCALL(publish_AddSoilCNPatchwithFOMFOM)
   integer :: id
   type(AddSoilCNPatchwithFOMFOMType) :: data
   end subroutine
   subroutine unpack_AddSoilCNPatchwithFOMFOM(variant, data)
   IMPORT :: AddSoilCNPatchwithFOMFOMType
   ml_external unpack_AddSoilCNPatchwithFOMFOM
!STDCALL(unpack_AddSoilCNPatchwithFOMFOM)
   integer :: variant
   type(AddSoilCNPatchwithFOMFOMType) :: data
   end subroutine
   subroutine publish_AddSoilCNPatchwithFOM(id, data)
   IMPORT :: AddSoilCNPatchwithFOMType
   ml_external publish_AddSoilCNPatchwithFOM
!STDCALL(publish_AddSoilCNPatchwithFOM)
   integer :: id
   type(AddSoilCNPatchwithFOMType) :: data
   end subroutine
   subroutine unpack_AddSoilCNPatchwithFOM(variant, data)
   IMPORT :: AddSoilCNPatchwithFOMType
   ml_external unpack_AddSoilCNPatchwithFOM
!STDCALL(unpack_AddSoilCNPatchwithFOM)
   integer :: variant
   type(AddSoilCNPatchwithFOMType) :: data
   end subroutine
   subroutine publish_MergeSoilCNPatch(id, data)
   IMPORT :: MergeSoilCNPatchType
   ml_external publish_MergeSoilCNPatch
!STDCALL(publish_MergeSoilCNPatch)
   integer :: id
   type(MergeSoilCNPatchType) :: data
   end subroutine
   subroutine unpack_MergeSoilCNPatch(variant, data)
   IMPORT :: MergeSoilCNPatchType
   ml_external unpack_MergeSoilCNPatch
!STDCALL(unpack_MergeSoilCNPatch)
   integer :: variant
   type(MergeSoilCNPatchType) :: data
   end subroutine
   subroutine publish_CNPatchVariablePatch(id, data)
   IMPORT :: CNPatchVariablePatchType
   ml_external publish_CNPatchVariablePatch
!STDCALL(publish_CNPatchVariablePatch)
   integer :: id
   type(CNPatchVariablePatchType) :: data
   end subroutine
   subroutine unpack_CNPatchVariablePatch(variant, data)
   IMPORT :: CNPatchVariablePatchType
   ml_external unpack_CNPatchVariablePatch
!STDCALL(unpack_CNPatchVariablePatch)
   integer :: variant
   type(CNPatchVariablePatchType) :: data
   end subroutine
   subroutine publish_CNPatchVariable(id, data)
   IMPORT :: CNPatchVariableType
   ml_external publish_CNPatchVariable
!STDCALL(publish_CNPatchVariable)
   integer :: id
   type(CNPatchVariableType) :: data
   end subroutine
   subroutine unpack_CNPatchVariable(variant, data)
   IMPORT :: CNPatchVariableType
   ml_external unpack_CNPatchVariable
!STDCALL(unpack_CNPatchVariable)
   integer :: variant
   type(CNPatchVariableType) :: data
   end subroutine
   subroutine publish_CNPatchPoolVariablePatchPool(id, data)
   IMPORT :: CNPatchPoolVariablePatchPoolType
   ml_external publish_CNPatchPoolVariablePatchPool
!STDCALL(publish_CNPatchPoolVariablePatchPool)
   integer :: id
   type(CNPatchPoolVariablePatchPoolType) :: data
   end subroutine
   subroutine unpack_CNPatchPoolVariablePatchPool(variant, data)
   IMPORT :: CNPatchPoolVariablePatchPoolType
   ml_external unpack_CNPatchPoolVariablePatchPool
!STDCALL(unpack_CNPatchPoolVariablePatchPool)
   integer :: variant
   type(CNPatchPoolVariablePatchPoolType) :: data
   end subroutine
   subroutine publish_CNPatchPoolVariablePatch(id, data)
   IMPORT :: CNPatchPoolVariablePatchType
   ml_external publish_CNPatchPoolVariablePatch
!STDCALL(publish_CNPatchPoolVariablePatch)
   integer :: id
   type(CNPatchPoolVariablePatchType) :: data
   end subroutine
   subroutine unpack_CNPatchPoolVariablePatch(variant, data)
   IMPORT :: CNPatchPoolVariablePatchType
   ml_external unpack_CNPatchPoolVariablePatch
!STDCALL(unpack_CNPatchPoolVariablePatch)
   integer :: variant
   type(CNPatchPoolVariablePatchType) :: data
   end subroutine
   subroutine publish_CNPatchPoolVariable(id, data)
   IMPORT :: CNPatchPoolVariableType
   ml_external publish_CNPatchPoolVariable
!STDCALL(publish_CNPatchPoolVariable)
   integer :: id
   type(CNPatchPoolVariableType) :: data
   end subroutine
   subroutine unpack_CNPatchPoolVariable(variant, data)
   IMPORT :: CNPatchPoolVariableType
   ml_external unpack_CNPatchPoolVariable
!STDCALL(unpack_CNPatchPoolVariable)
   integer :: variant
   type(CNPatchPoolVariableType) :: data
   end subroutine
   subroutine publish_CNPatchVariable_arrayPool(id, data)
   IMPORT :: CNPatchVariable_arrayPoolType
   ml_external publish_CNPatchVariable_arrayPool
!STDCALL(publish_CNPatchVariable_arrayPool)
   integer :: id
   type(CNPatchVariable_arrayPoolType) :: data
   end subroutine
   subroutine unpack_CNPatchVariable_arrayPool(variant, data)
   IMPORT :: CNPatchVariable_arrayPoolType
   ml_external unpack_CNPatchVariable_arrayPool
!STDCALL(unpack_CNPatchVariable_arrayPool)
   integer :: variant
   type(CNPatchVariable_arrayPoolType) :: data
   end subroutine
   subroutine publish_CNPatchVariable_array(id, data)
   IMPORT :: CNPatchVariable_arrayType
   ml_external publish_CNPatchVariable_array
!STDCALL(publish_CNPatchVariable_array)
   integer :: id
   type(CNPatchVariable_arrayType) :: data
   end subroutine
   subroutine unpack_CNPatchVariable_array(variant, data)
   IMPORT :: CNPatchVariable_arrayType
   ml_external unpack_CNPatchVariable_array
!STDCALL(unpack_CNPatchVariable_array)
   integer :: variant
   type(CNPatchVariable_arrayType) :: data
   end subroutine
   subroutine publish_SoluteChanged(id, data)
   IMPORT :: SoluteChangedType
   ml_external publish_SoluteChanged
!STDCALL(publish_SoluteChanged)
   integer :: id
   type(SoluteChangedType) :: data
   end subroutine
   subroutine unpack_SoluteChanged(variant, data)
   IMPORT :: SoluteChangedType
   ml_external unpack_SoluteChanged
!STDCALL(unpack_SoluteChanged)
   integer :: variant
   type(SoluteChangedType) :: data
   end subroutine
   subroutine publish_SupplementBuy(id, data)
   IMPORT :: SupplementBuyType
   ml_external publish_SupplementBuy
!STDCALL(publish_SupplementBuy)
   integer :: id
   type(SupplementBuyType) :: data
   end subroutine
   subroutine unpack_SupplementBuy(variant, data)
   IMPORT :: SupplementBuyType
   ml_external unpack_SupplementBuy
!STDCALL(unpack_SupplementBuy)
   integer :: variant
   type(SupplementBuyType) :: data
   end subroutine
   subroutine publish_Feed(id, data)
   IMPORT :: FeedType
   ml_external publish_Feed
!STDCALL(publish_Feed)
   integer :: id
   type(FeedType) :: data
   end subroutine
   subroutine unpack_Feed(variant, data)
   IMPORT :: FeedType
   ml_external unpack_Feed
!STDCALL(unpack_Feed)
   integer :: variant
   type(FeedType) :: data
   end subroutine
   subroutine publish_OnConserve(id, data)
   IMPORT :: OnConserveType
   ml_external publish_OnConserve
!STDCALL(publish_OnConserve)
   integer :: id
   type(OnConserveType) :: data
   end subroutine
   subroutine unpack_OnConserve(variant, data)
   IMPORT :: OnConserveType
   ml_external unpack_OnConserve
!STDCALL(unpack_OnConserve)
   integer :: variant
   type(OnConserveType) :: data
   end subroutine
   subroutine publish_Mix(id, data)
   IMPORT :: MixType
   ml_external publish_Mix
!STDCALL(publish_Mix)
   integer :: id
   type(MixType) :: data
   end subroutine
   subroutine unpack_Mix(variant, data)
   IMPORT :: MixType
   ml_external unpack_Mix
!STDCALL(unpack_Mix)
   integer :: variant
   type(MixType) :: data
   end subroutine
   subroutine publish_SaveCheckpoint(id, data)
   IMPORT :: SaveCheckpointType
   ml_external publish_SaveCheckpoint
!STDCALL(publish_SaveCheckpoint)
   integer :: id
   type(SaveCheckpointType) :: data
   end subroutine
   subroutine unpack_SaveCheckpoint(variant, data)
   IMPORT :: SaveCheckpointType
   ml_external unpack_SaveCheckpoint
!STDCALL(unpack_SaveCheckpoint)
   integer :: variant
   type(SaveCheckpointType) :: data
   end subroutine
   subroutine publish_RestoreCheckpoint(id, data)
   IMPORT :: RestoreCheckpointType
   ml_external publish_RestoreCheckpoint
!STDCALL(publish_RestoreCheckpoint)
   integer :: id
   type(RestoreCheckpointType) :: data
   end subroutine
   subroutine unpack_RestoreCheckpoint(variant, data)
   IMPORT :: RestoreCheckpointType
   ml_external unpack_RestoreCheckpoint
!STDCALL(unpack_RestoreCheckpoint)
   integer :: variant
   type(RestoreCheckpointType) :: data
   end subroutine
   subroutine publish_ExternalMassFlow(id, data)
   IMPORT :: ExternalMassFlowType
   ml_external publish_ExternalMassFlow
!STDCALL(publish_ExternalMassFlow)
   integer :: id
   type(ExternalMassFlowType) :: data
   end subroutine
   subroutine unpack_ExternalMassFlow(variant, data)
   IMPORT :: ExternalMassFlowType
   ml_external unpack_ExternalMassFlow
!STDCALL(unpack_ExternalMassFlow)
   integer :: variant
   type(ExternalMassFlowType) :: data
   end subroutine
   subroutine publish_RunoffEvent(id, data)
   IMPORT :: RunoffEventType
   ml_external publish_RunoffEvent
!STDCALL(publish_RunoffEvent)
   integer :: id
   type(RunoffEventType) :: data
   end subroutine
   subroutine unpack_RunoffEvent(variant, data)
   IMPORT :: RunoffEventType
   ml_external unpack_RunoffEvent
!STDCALL(unpack_RunoffEvent)
   integer :: variant
   type(RunoffEventType) :: data
   end subroutine
   subroutine publish_KeyValueArraypair_list(id, data)
   IMPORT :: KeyValueArraypair_listType
   ml_external publish_KeyValueArraypair_list
!STDCALL(publish_KeyValueArraypair_list)
   integer :: id
   type(KeyValueArraypair_listType) :: data
   end subroutine
   subroutine unpack_KeyValueArraypair_list(variant, data)
   IMPORT :: KeyValueArraypair_listType
   ml_external unpack_KeyValueArraypair_list
!STDCALL(unpack_KeyValueArraypair_list)
   integer :: variant
   type(KeyValueArraypair_listType) :: data
   end subroutine
   subroutine publish_KeyValueArray(id, data)
   IMPORT :: KeyValueArrayType
   ml_external publish_KeyValueArray
!STDCALL(publish_KeyValueArray)
   integer :: id
   type(KeyValueArrayType) :: data
   end subroutine
   subroutine unpack_KeyValueArray(variant, data)
   IMPORT :: KeyValueArrayType
   ml_external unpack_KeyValueArray
!STDCALL(unpack_KeyValueArray)
   integer :: variant
   type(KeyValueArrayType) :: data
   end subroutine
   subroutine publish_ChangeGSMax(id, data)
   IMPORT :: ChangeGSMaxType
   ml_external publish_ChangeGSMax
!STDCALL(publish_ChangeGSMax)
   integer :: id
   type(ChangeGSMaxType) :: data
   end subroutine
   subroutine unpack_ChangeGSMax(variant, data)
   IMPORT :: ChangeGSMaxType
   ml_external unpack_ChangeGSMax
!STDCALL(unpack_ChangeGSMax)
   integer :: variant
   type(ChangeGSMaxType) :: data
   end subroutine
   subroutine publish_AvailableToAnimalelement(id, data)
   IMPORT :: AvailableToAnimalelementType
   ml_external publish_AvailableToAnimalelement
!STDCALL(publish_AvailableToAnimalelement)
   integer :: id
   type(AvailableToAnimalelementType) :: data
   end subroutine
   subroutine unpack_AvailableToAnimalelement(variant, data)
   IMPORT :: AvailableToAnimalelementType
   ml_external unpack_AvailableToAnimalelement
!STDCALL(unpack_AvailableToAnimalelement)
   integer :: variant
   type(AvailableToAnimalelementType) :: data
   end subroutine
   subroutine publish_AvailableToAnimal(id, data)
   IMPORT :: AvailableToAnimalType
   ml_external publish_AvailableToAnimal
!STDCALL(publish_AvailableToAnimal)
   integer :: id
   type(AvailableToAnimalType) :: data
   end subroutine
   subroutine unpack_AvailableToAnimal(variant, data)
   IMPORT :: AvailableToAnimalType
   ml_external unpack_AvailableToAnimal
!STDCALL(unpack_AvailableToAnimal)
   integer :: variant
   type(AvailableToAnimalType) :: data
   end subroutine
   subroutine publish_RemovedByAnimalelement(id, data)
   IMPORT :: RemovedByAnimalelementType
   ml_external publish_RemovedByAnimalelement
!STDCALL(publish_RemovedByAnimalelement)
   integer :: id
   type(RemovedByAnimalelementType) :: data
   end subroutine
   subroutine unpack_RemovedByAnimalelement(variant, data)
   IMPORT :: RemovedByAnimalelementType
   ml_external unpack_RemovedByAnimalelement
!STDCALL(unpack_RemovedByAnimalelement)
   integer :: variant
   type(RemovedByAnimalelementType) :: data
   end subroutine
   subroutine publish_RemovedByAnimal(id, data)
   IMPORT :: RemovedByAnimalType
   ml_external publish_RemovedByAnimal
!STDCALL(publish_RemovedByAnimal)
   integer :: id
   type(RemovedByAnimalType) :: data
   end subroutine
   subroutine unpack_RemovedByAnimal(variant, data)
   IMPORT :: RemovedByAnimalType
   ml_external unpack_RemovedByAnimal
!STDCALL(unpack_RemovedByAnimal)
   integer :: variant
   type(RemovedByAnimalType) :: data
   end subroutine
   subroutine publish_transact(id, data)
   IMPORT :: transactType
   ml_external publish_transact
!STDCALL(publish_transact)
   integer :: id
   type(transactType) :: data
   end subroutine
   subroutine unpack_transact(variant, data)
   IMPORT :: transactType
   ml_external unpack_transact
!STDCALL(unpack_transact)
   integer :: variant
   type(transactType) :: data
   end subroutine
   subroutine publish_OutputListoutputs(id, data)
   IMPORT :: OutputListoutputsType
   ml_external publish_OutputListoutputs
!STDCALL(publish_OutputListoutputs)
   integer :: id
   type(OutputListoutputsType) :: data
   end subroutine
   subroutine unpack_OutputListoutputs(variant, data)
   IMPORT :: OutputListoutputsType
   ml_external unpack_OutputListoutputs
!STDCALL(unpack_OutputListoutputs)
   integer :: variant
   type(OutputListoutputsType) :: data
   end subroutine
   subroutine publish_OutputList(id, data)
   IMPORT :: OutputListType
   ml_external publish_OutputList
!STDCALL(publish_OutputList)
   integer :: id
   type(OutputListType) :: data
   end subroutine
   subroutine unpack_OutputList(variant, data)
   IMPORT :: OutputListType
   ml_external unpack_OutputList
!STDCALL(unpack_OutputList)
   integer :: variant
   type(OutputListType) :: data
   end subroutine
   subroutine publish_RootSystemZone(id, data)
   IMPORT :: RootSystemZoneType
   ml_external publish_RootSystemZone
!STDCALL(publish_RootSystemZone)
   integer :: id
   type(RootSystemZoneType) :: data
   end subroutine
   subroutine unpack_RootSystemZone(variant, data)
   IMPORT :: RootSystemZoneType
   ml_external unpack_RootSystemZone
!STDCALL(unpack_RootSystemZone)
   integer :: variant
   type(RootSystemZoneType) :: data
   end subroutine
   subroutine publish_RootSystem(id, data)
   IMPORT :: RootSystemType
   ml_external publish_RootSystem
!STDCALL(publish_RootSystem)
   integer :: id
   type(RootSystemType) :: data
   end subroutine
   subroutine unpack_RootSystem(variant, data)
   IMPORT :: RootSystemType
   ml_external unpack_RootSystem
!STDCALL(unpack_RootSystem)
   integer :: variant
   type(RootSystemType) :: data
   end subroutine
   subroutine publish_Earn(id, data)
   IMPORT :: EarnType
   ml_external publish_Earn
!STDCALL(publish_Earn)
   integer :: id
   type(EarnType) :: data
   end subroutine
   subroutine unpack_Earn(variant, data)
   IMPORT :: EarnType
   ml_external unpack_Earn
!STDCALL(unpack_Earn)
   integer :: variant
   type(EarnType) :: data
   end subroutine
   subroutine publish_Spend(id, data)
   IMPORT :: SpendType
   ml_external publish_Spend
!STDCALL(publish_Spend)
   integer :: id
   type(SpendType) :: data
   end subroutine
   subroutine unpack_Spend(variant, data)
   IMPORT :: SpendType
   ml_external unpack_Spend
!STDCALL(unpack_Spend)
   integer :: variant
   type(SpendType) :: data
   end subroutine
   subroutine publish_Report(id, data)
   IMPORT :: ReportType
   ml_external publish_Report
!STDCALL(publish_Report)
   integer :: id
   type(ReportType) :: data
   end subroutine
   subroutine unpack_Report(variant, data)
   IMPORT :: ReportType
   ml_external unpack_Report
!STDCALL(unpack_Report)
   integer :: variant
   type(ReportType) :: data
   end subroutine

   end interface
end module dataTypesInterface

